### PR TITLE
Add predefined angles and finish affirmation #1

### PR DESCRIPTION
**Pull request by ak-seyam**
**this is what i've done thus far**
1- added predefined angles
2- add option to chose predef or slider angle
Note: the red rect shows a value from a slider
result

### CODE REVIEW

**Comment by ak-seyam** [comment]
**Conflicts Tldr; :**
- added a useless module for something I've realized later it wasn't necessary    
- the version modifications you've did i suggest marking them as version 0.x where x is (the number of affirmations to be accomplished in this particular verion) + previous version where => (0.9 + 0.1 == 0.10)

**Comment by ak-seyam** [comment]
Wel, no I think we should do it in react it will provide much flexibility and a better UI experience

**Review by abdo1819 — APPROVED** [review]
nice work i just removed unused imports from utils

**Comment by abdo1819** [comment]
> Wel, no I think we should do it in react it will provide much flexibility and a better UI experience

i wanna the app to be usable without any internet connection 

we may use other minimal front framework if can be ship locally 
i will search if there is any good option

beside i am thinking of removing the middle server after development is complete -if no extra proceeding required- and manage every thing from control server which has very small memory

**Pull request merged**
